### ISSUE TITLE
Major error causing map names in roll20 to stack

### ISSUE THREAD

**Issue by Vampiregoat69** [SSStormy/roll20-enhancement-suite#1]
AnimatedBackgroundLayer.js:1 (t.err_report_missing_current_runner_in)
AnimatedBackgroundLayer.js:1 (t.endVideo)
AnimatedBackgroundLayer.js:1 (t.cleanupPage)
AnimatedBackgroundLayer.js:1 (r.initPage)
AnimatedBackgroundLayer.js:1 (t.setup)
WebsiteBootstrap.js:18 (e.fire)
WebsiteBootstrap.js:18 (window.r20es.onLoadingOverlayHide)
blob:https://app.roll20.net/8fb1dc73-5c07-4a27-871a-0dce5e88ea0b:587 (anonymous function)
blob:https://app.roll20.net/ef9c2b07-032b-4124-a9b0-17cf0a6bb7ad:9287 (opt.complete)
blob:https://app.roll20.net/ef9c2b07-032b-4124-a9b0-17cf0a6bb7ad:1039 (fire)
blob:https://app.roll20.net/ef9c2b07-032b-4124-a9b0-17cf0a6bb7ad:1150 (fireWith)
blob:https://app.roll20.net/ef9c2b07-032b-4124-a9b0-17cf0a6bb7ad:8738 (tick)
blob:https://app.roll20.net/ef9c2b07-032b-4124-a9b0-17cf0a6bb7ad:9319 (jQuery.fx.tick)
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
!function(e){var n={};function t(r){if(n[r])return n[r].exports;var i=n[r]={i:r,l:!1,exports:{}};return e[r].call(i.exports,i,i.exports,t),i.l=!0,i.exports}t.m=e,t.c=n,t.d=function(e,n,r){t.o(e,n)||Object.defineProperty(e,n,{enumerable:!0,get:r})},t.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},t.t=function(e,n){if(1&n&&(e=t(e)),8&n)return e;if(4&n&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(t.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&n&&"string"!=typeof e)for(var i in e)t.d(r,i,function(n){return e[n]}.bind(null,i));return r},t.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(n,"a",n),n},t.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},t.p="",t(t.s=100)}({10:function(e,n,t){"use strict";n.__esModule=!0;var r=t(2),i=t(6),o=function(){function e(e,n,t){var i=this;this.success=!1,this.getRoot=function(){return i._root},this.getId=function(){return i._id},this.isSuccessful=function(){return i.success},this.setData=function(e){return i.returnData=e},window.r20esDialogId="r20esDialogId"in window?window.r20esDialogId:0,this.centerWorkaround=null!==t&&void 0!==t&&t,this._id="r20es-dialog-"+window.r20esDialogId++,this._root=r.DOM.createElement("dialog",{className:e,style:n,id:this.getId()}),document.body.insertBefore(this.getRoot(),document.body.firstElementChild),window.dialogPolyfill&&window.dialogPolyfill.registerDialog(this.getRoot()),this.close=this.close.bind(this),this.dispose=this.dispose.bind(this)}return e.prototype.internalRender=function(){var e=this;this.getRoot().appendChild(this.render()),window.dialogPolyfill&&window.dialogPolyfill.reposition(this.getRoot()),this.centerWorkaround&&setTimeout(function(){e.recenter()},100)},e.prototype.recenter=function(){var e=this.getRoot(),n=document.body.scrollTop||document.documentElement.scrollTop,t=n+(window.innerHeight-e.offsetHeight)/2;e.style.top=Math.max(n,t)+"px"},e.prototype.rerender=function(){i.removeAllChildren(this.getRoot()),this.internalRender()},e.prototype.internalShow=function(){i.removeAllChildren(this.getRoot()),this.success=!1,this.internalRender(),this.getRoot().showModal()},e.prototype.getData=function(){var e=this.returnData;return this.returnData=null,e},e.prototype.close=function(e){void 0===e&&(e=!1),this.success="boolean"==typeof e&&e,this.getRoot().open&&this.getRoot().close()},e.prototype.dispose=function(){this.close(),i.findByIdAndRemove(this.getId())},e}();n.DialogBase=o},100:function(e,n,t){"use strict";(function(e){var r=this&&this.__extends||function(){var e=function(n,t){return(e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,n){e.__proto__=n}||function(e,n){for(var t in n)n.hasOwnProperty(t)&&(e[t]=n[t])})(n,t)};return function(n,t){function r(){this.constructor=n}e(n,t),n.prototype=null===t?Object.create(t):(r.prototype=t.prototype,new r)}}(),i=this&&this.__assign||function(){return(i=Object.assign||function(e){for(var n,t=1,r=arguments.length;t<r;t++)for(var i in n=arguments[t])Object.prototype.hasOwnProperty.call(n,i)&&(e[i]=n[i]);return e}).apply(this,arguments)};n.__esModule=!0;var o=t(4),a=t(5),s=t(2),u=t(77),c=t(7),l=t(78),d=t(12),f=t(10),p=t(11),g=t(79),h=t(6),m=function(){function e(){}return e.get_video_source=function(e){var n=e.attributes[w.propVideoSource];return"string"!=typeof n?"":n},e.get_main_canvas=function(){var e=$("#maincanvas")[0]||$("#finalcanvas")[0];return e||console.error("[AnimatedBackgrounds] could not find beforeRoot!"),e},e.get_canvas_root_size=function(n){if(void 0===n&&(n=void 0),n||(n=e.get_main_canvas()),!n)return{x:0,y:0};var t=n.parentElement;return{x:parseInt(t.style.width.replace("px","")),y:parseInt(t.style.height.replace("px",""))}},e.is_anim_enabled=function(e){var n=e.attributes[w.propVideoEnabled];return"boolean"==typeof n&&n},e.set_anim_enabled=function(e,n){var t;e.save(((t={})[w.propVideoEnabled]=n,t))},e.set_video_source=function(e,n){var t;return e.save(((t={})[w.propVideoSource]=n,t))},e}(),v=function(){function e(){var e=this;this.on_setting_change=function(n,t,r){"muteAudio"===n&&e.video&&(e.video.muted=r),"audioVolume"===n&&e.video&&e.set_volume(r)},this.on_zoom=function(n){console.log("video SET ZOOM",n),e.ctx&&(e.ctx.restore(),e.ctx.save(),e.ctx.scale(n,n))},this.init=function(n,t){e.ctx=t.getContext("2d"),e.ctx.save(),e.video=s.DOM.createElement("video",{loop:!0,autoplay:!0,muted:n.muteAudio}),e.set_volume(n.audioVolume)},this.can_play=function(e){return m.get_video_source(e).length>0&&m.is_anim_enabled(e)},this.render_frame=function(n,t,r,i){if(e.ctx&&e.video){var o=70*n.attributes.width,s=70*n.attributes.height,u=l.scaleToFit(e.video.videoWidth,e.video.videoHeight,o,s);e.ctx.drawImage(e.video,-a.R20.getCanvasOffsetX(),-a.R20.getCanvasOffsetY(),u.x,u.y);var c=Math.ceil(a.R20.getCanvasWidth()/a.R20.getCanvasZoom()),d=a.R20.getCanvasHeight()/a.R20.getCanvasZoom();return e.ctx.fillStyle=n.attributes.background_color,e.ctx.fillRect(0,u.y-a.R20.getCanvasOffsetY(),c,d),e.ctx.fillRect(u.x-a.R20.getCanvasOffsetX(),0,c,d),!0}return!1},this.start=function(n,t){e.video.src=m.get_video_source(n),e.video.play()},this.end=function(n){n.style.display="none",e.video.pause(),e.video.src=""},this.dispose=function(){e.ctx&&(e.ctx=null),e.video&&(e.video=null)}}return e.prototype.set_volume=function(e){if(this.video)try{this.video.volume=e}catch(e){this.video.volume=.1}},e}(),w=function(n){function t(){var r=n.call(this,e)||this;return r._isPlaying=!1,r._events=[],r.render_loop=function(e){r._isPlaying&&r.current_page&&r.current_runner&&r.current_runner.render_frame(r.current_page,r.canvas,r.roll20Canvas,e)&&requestAnimationFrame(r.render_loop)},r.beginVideo=function(){if(r.current_runner){console.log("[AnimBackgrounds] beginVideo while current_runner"),r._isPlaying=!0,r.canvas.style.display="block";var e=function(){try{r.current_runner.start(r.current_page,r.canvas),console.log("[AnimBackgrounds] current_runner.start succeeded!")}catch(e){console.error(e)}};if(e(),d.isChromium())for(var n=["mousedown","scroll","keydown"],t=function(){e();for(var r=0,i=n;r<i.length;r++){var o=i[r];document.body.removeEventListener(o,t)}},i=0,o=n;i<o.length;i++){var s=o[i];document.body.addEventListener(s,t)}r.onResizeCanvas(a.R20.getCanvasWidth(),a.R20.getCanvasHeight()),r.onSetZoom(a.R20.getCanvasZoom()),requestAnimationFrame(r.render_loop),a.R20.renderAll()}else r.err_report_missing_current_runner_in("beginVideo")},r.onPropChange=function(){r.current_runner&&(console.log("[AnimBackgrounds] onPropChange while current_runner"),r.endVideo(),r.current_runner.can_play(r.current_page)&&r.beginVideo())},r.initPage=function(){r.cleanupPage();var e=a.R20.getCurrentPage(),n=function(){return e};r._events=[c.EventSubscriber.subscribe("change:"+t.propVideoSource,r.onPropChange,n),c.EventSubscriber.subscribe("change:"+t.propVideoEnabled,r.onPropChange,n),c.EventSubscriber.subscribe("change:height",r.onPropChange,n),c.EventSubscriber.subscribe("change:width",r.onPropChange,n)],r.current_page=e,a.R20.renderAll(),r.canvas=s.DOM.createElement("canvas",null);var i=m.get_main_canvas();i&&(i.parentNode.insertBefore(r.canvas,i),r.canvas.width=i.width,r.canvas.height=i.height,r.roll20Canvas=i);var o=r.getHook().config;r.current_runner=new v,r.current_runner.init(o,r.canvas),r.current_runner&&r.current_runner.can_play(r.current_page)&&r.beginVideo()},r.onResizeCanvas=function(e,n){r._isPlaying&&(console.log("[AnimBackgrounds] onResizeCanvas while _isPlaying"),r.canvas.width=e,r.canvas.height=n,r.onSetZoom(a.R20.getCanvasZoom()))},r.overrideSetCanvasSize=function(e,n){r._originalResize(e,n),r.onResizeCanvas(e,n)},r.onSetZoom=function(e){r._isPlaying&&(console.log("[AnimBackgrounds] onSetZoom while _isPlaying"),r.current_runner.on_zoom(e))},r.ui_show_configuration_dialog=function(){r._dialog.show(r,r.current_page)},r.trampoline_draw_background=function(e,n){if(r._isPlaying){var t=e.fillStyle,i=e.globalCompositeOperation;e.fillStyle="rgba(0,0,0,0)",e.globalCompositeOperation="copy";var o=a.R20.getCanvasZoom();e.fillRect(0,0,Math.ceil(a.R20.getCanvasWidth()/o),Math.ceil(a.R20.getCanvasHeight()/o)),e.fillStyle=t,e.globalCompositeOperation=i}else r.original_canvas_overlay_draw_background(e,n)},r}return r(t,n),t.prototype.err_report_missing_current_runner_in=function(e){console.error("["+e+"]: current_runner is null, bailing.")},t.prototype.endVideo=function(){this.current_runner?(console.log("[AnimBackgrounds] endVideo while current_runner"),this._isPlaying=!1,this.current_runner.end(this.canvas),a.R20.renderAll()):this.err_report_missing_current_runner_in("endVideo")},t.prototype.cleanupPage=function(){console.log("[AnimBackgrounds] cleanupPage"),this.endVideo();for(var e=0,n=this._events;e<n.length;e++){n[e].unsubscribe()}this.current_runner&&this.current_runner.dispose(),this.canvas&&(this.canvas.remove(),this.canvas=null)},t.prototype.onSettingChange=function(e,n,t){this.current_runner&&(console.log("[AnimBackgrounds] onSettingChange while current_runner"),this.current_runner.on_setting_change(e,n,t))},t.prototype.setup=function(){if(console.log("video before =================================="),this._originalResize=window.d20.engine.setCanvasSize,window.d20.engine.setCanvasSize=this.overrideSetCanvasSize,window.r20es.onZoomChange=this.onSetZoom,window.r20es.onResizeCanvas=this.onResizeCanvas,this.original_canvas_overlay_draw_background=window.d20.canvas_overlay.drawBackground,window.d20.canvas_overlay.drawBackground=this.trampoline_draw_background,this.initPage(),window.r20es.onPageChange.on(this.initPage),a.R20.isGM()){this._showSettingsWidget=s.DOM.createElement("div",{title:"Animated Background Setup (VTTES)",style:{cursor:"pointer",position:"absolute",top:"0",right:"400px",maxWidth:"32px",maxHeight:"32px",zIndex:"10",backgroundColor:"#e18e42",borderRadius:"2px"},onClick:this.ui_show_configuration_dialog},s.DOM.createElement("img",{src:"https://github.com/encharm/Font-Awesome-SVG-PNG/raw/master/black/png/32/film.png",width:"28",height:"28",alt:"ANIM"})),document.body.appendChild(this._showSettingsWidget),console.log(this._showSettingsWidget)}this._dialog=new y},t.prototype.dispose=function(){n.prototype.dispose.call(this),this.cleanupPage(),window.d20.engine.setCanvasSize=this._originalResize,window.r20es.onZoomChange=null,window.r20es.onResizeCanvas=null,window.d20.canvas_overlay.drawBackground=this.original_canvas_overlay_draw_background,this.original_canvas_overlay_draw_background=null,this._showSettingsWidget.remove(),this._showSettingsWidget=null,this._dialog.dispose(),this.current_runner&&this.current_runner.dispose,window.r20es.onPageChange.off(this.initPage)},t.propVideoSource="r20es_video_src",t.propVideoEnabled="r20es_video_enabled",t}(o.R20Module.OnAppLoadBase),_=function(e,n,t){var r=document.createElement("video");r.crossorigin="anonymous",r.volume=0;var i=function(){r.pause(),r.removeEventListener("error",o),r.removeEventListener("canplay",a),r.src=""},o=function(e){i(),console.error("check_if_url_is_video_stream error:",e),t()},a=function(e){i(),n()};r.addEventListener("error",o),r.addEventListener("canplay",a),r.src=e,console.log(e),r.play()},y=function(e){function n(){var n=e.call(this)||this;return n.onChangeEnabled=function(e){m.set_anim_enabled(n.page,e.target.checked)},n.ui_is_invalid_media_url=!1,n.onBlurUrl=function(e){e.stopPropagation(),n.ui_on_update_url_input(e.target.value)},n.ui_on_update_url_input=function(e){m.set_video_source(n.page,e),n.ui_verify_media_url(e,!0)},n.module_get_history=function(){return n.parent_module.getHook().config.video_history},n.module_save_history=function(e){return n.parent_module.setConfigValue("video_history",e)},n.ui_verify_media_url=function(e,t){_(e,function(){if(t){var r=n.module_get_history();g.removeByReference(r,e),r.unshift(e),n.module_save_history(r)}n.ui_is_invalid_media_url=!1,n.rerender()},function(){n.ui_is_invalid_media_url=!0,n.rerender()})},n.ui_toggle_history=function(){n.show_history=!n.show_history,n.rerender()},n.show_history=!1,n.ui_history_url_attrib="url",n.ui_history_retrieve_url=function(e){return e.target.getAttribute(n.ui_history_url_attrib)},n.ui_history_remove=function(e){var t=n.ui_history_retrieve_url(e),r=n.module_get_history();g.removeByReference(r,t),n.module_save_history(r),n.rerender()},n.ui_history_select=function(e){var t=n.ui_history_retrieve_url(e);n.ui_on_update_url_input(t)},n}return r(n,e),n.prototype.show=function(e,n){this.parent_module=e,this.page=n,this.internalShow(),this.ui_verify_media_url(m.get_video_source(n),!1)},n.prototype.render=function(){var e=this,n=this.module_get_history(),t=[],r=m.is_anim_enabled(this.page),o=m.get_video_source(this.page);if(this.show_history){for(var a=function(n,t){return n.setAttribute(e.ui_history_url_attrib,t)},c=0,l=n;c<l.length;c++){var d=l[c],f={width:"auto",marginRight:"8px"},g=s.DOM.createElement("input",{style:f,className:"btn btn-danger",type:"button",value:"X",onClick:this.ui_history_remove}),v=s.DOM.createElement("input",{style:f,className:"btn btn-success",type:"button",value:"Use",onClick:this.ui_history_select}),w=s.DOM.createElement("span",{title:d},h.nearly_format_file_url(d));a(g,d),a(v,d),t.push(s.DOM.createElement("div",null,g,v,w))}0==n.length&&t.push(s.DOM.createElement("div",null,"Nothing here!"))}var _=s.DOM.createElement("span",null);return this.ui_is_invalid_media_url?(s.DOM.apply_style(_,i({float:"right"},u.CommonStyle.error_span)),_.innerText="Invalid: Not a direct video stream"):(s.DOM.apply_style(_,i({float:"right"},u.CommonStyle.success_span)),_.innerText="URL is valid!"),s.DOM.createElement(p.Dialog,null,s.DOM.createElement(p.DialogHeader,null,s.DOM.createElement("h2",null,"Animated Background Setup")),s.DOM.createElement(p.DialogBody,null,s.DOM.createElement("div",null,s.DOM.createElement("i",null,"Disclaimer: Players must have VTTES installed to be able to see the animated background.")),s.DOM.createElement("br",null),s.DOM.createElement("div",{style:{display:"grid",gridTemplateColumns:"auto auto",rowGap:"4px"}},s.DOM.createElement("b",null,"Enabled?"),s.DOM.createElement("div",null,s.DOM.createElement("input",{type:"checkbox",onChange:this.onChangeEnabled,checked:r})),s.DOM.createElement("span",null,s.DOM.createElement("b",null,"Media URL "),s.DOM.createElement("i",null,"(must be a direct stream)")),s.DOM.createElement("div",null,s.DOM.createElement("input",{style:{paddingLeft:"8px"},type:"text",onBlur:this.onBlurUrl,value:o}))),s.DOM.createElement("div",null,_),s.DOM.createElement("br",null),s.DOM.createElement("button",{style:"btn",onClick:this.ui_toggle_history},this.show_history?"Hide History":"Show History"),s.DOM.createElement("br",null),s.DOM.createElement("div",{style:{maxHeight:"500px",overflowY:"auto"}},t)),s.DOM.createElement(p.DialogFooter,null,s.DOM.createElement(p.DialogFooterContent,null,s.DOM.createElement("button",{style:{boxSizing:"border-box",width:"100%"},className:"btn btn-primary",onClick:this.close},"OK"))))},n}(f.DialogBase);o.R20Module.canInstall()&&(new w).install()}).call(this,"src/modules/AnimatedBackgroundLayer")},11:function(e,n,t){"use strict";var r=this&&this.__extends||function(){var e=function(n,t){return(e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,n){e.__proto__=n}||function(e,n){for(var t in n)n.hasOwnProperty(t)&&(e[t]=n[t])})(n,t)};return function(n,t){function r(){this.constructor=n}e(n,t),n.prototype=null===t?Object.create(t):(r.prototype=t.prototype,new r)}}();n.__esModule=!0;var i=t(2),o=t(6),a=function(e){function n(n,t,r){var o=e.call(this,t,r)||this;return o.show=o.internalShow,o.render=function(){return i.DOM.createElement(u,null,i.DOM.createElement(s,null,i.DOM.createElement("h3",null,o.action,", please wait...")))},o.action=n,o}return r(n,e),n}(t(10).DialogBase);function s(e){return i.DOM.createElement("div",{className:"dialog-body"})}function u(e){return i.DOM.createElement("div",{className:"r20es-dialog"})}n.LoadingDialog=a,n.DialogHeader=function(e){return i.DOM.createElement("div",{className:"dialog-header"})},n.DialogBody=s,n.DialogFooter=function(e){return i.DOM.createElement("div",{className:"dialog-footer"},i.DOM.createElement("hr",null))},n.DialogFooterContent=function(e){return i.DOM.createElement("div",{className:"dialog-footer-content"})},n.Dialog=u,n.CheckboxWithText=function(e){var n=o.copy(e,{style:{verticalAlign:"middle",marginRight:"4px"},type:"checkbox"}),t=i.DOM.createElement("input",n),r=n&&n.component||"div";return i.DOM.createElement(r,null,t,i.DOM.createElement("span",{style:{verticalAlign:"middle"}},n.checkboxText))}},12:function(e,n,t){"use strict";n.__esModule=!0;var r=t(13),i=function(){var e=r.default();return"chrome"===e.name||"opera"===e.name};n.isChromium=i;n.doesBrowserNotSupportResponseFiltering=function(){var e=r.default();return console.log(e),!!i()||"firefox"===e.name&&e.versionNumber<57}},13:function(e,n,t){"use strict";t.r(n),function(e){
/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */
var t=Object.assign||function(e){for(var n,t=1,r=arguments.length;t<r;t++)for(var i in n=arguments[t

**Comment by justas-d** [comment]
The alternative page toolbar is broken right now. Please disable the alternative page toolbar module for now.

**Comment by justas-d** [comment]
Fixed in 1.15.35
