### ISSUE TITLE
Additional Export Suggestions: Pages (maps) and Handouts

### ISSUE THREAD

**Issue by wertercatt** [SSStormy/roll20-enhancement-suite#113]
If these could be exported, non-paid Roll20 campaigns could be completely backed up locally.

**Comment by SSStormy** [comment]
First off, Hi! Thanks for opening an issue.

For pages, you'll want to take a look at betteR20 as it already has that in the form of the Module Exporter (unsure if they properly support handouts). I'd like to steer R20ES in such a way that the feature sets of R20ES and B20 overlap as little as possible.

Now when it comes to handouts, I highly doubt that importing/exporting them as JSON files is very useful. You can already copy/paste the text (albeit without the proper formatting). If we were to implement handout IO, how could we do it in such a way that it's useful?

In general, if you are looking for a full campaign export, I extremely recommend trying out betteR20's Module Exporter.

**Comment by wertercatt** [comment]
I wasn't aware that betteR20 had that feature, thanks for informing me 👍
