### ISSUE TITLE
Token Editor (Typo)

### ISSUE THREAD

**Issue by Wenneker** [SSStormy/roll20-enhancement-suite#114]
When the Default Token is undefined

There is an extra quotation mark

![image](https://user-images.githubusercontent.com/2795819/46247438-199b7600-c3d1-11e8-9b18-8d9ec2b90ebf.png)

**Comment by SSStormy** [comment]
Fixed by https://github.com/SSStormy/roll20-enhancement-suite/commit/b934a0ad25808aa47142e777a6748a30286094ef#diff-512976fba1cabf1d9b11a466ee2de1f4L285
