### ISSUE TITLE
Token Editor Page (missing) features (ideas)

### ISSUE THREAD

**Issue by Blue64** [SSStormy/roll20-enhancement-suite#138]
I like what you have done with the Token Editor so far, especially the Advanced Fog of War settings, plan to use that at a later date when I get my game finished (so much World Building & indexing, so little time). However, I have noticed that you have a few features lacking on the Token Editor Page:
- You are lacking an Orientation option.
  - Flip Vertical
  - Flip Horizontal
  - Face Direction
- You are lacking a Resize Token Button (on the Token Editor Page) which will Resize the Token; using its current Size parameters as it's maximum settings.
  - using a 100×50 Picture:
    - 100×100 becomes 100×50
    - 90×90 becomes 90×45
    - 70×70 becomes 70×35
    - 50×50 becomes 50×25
- you are lacking the "Is Drawing" setting as well

**Comment by SSStormy** [comment]
Hi.
I'l take a look at orientation options.
Unsure what you mean by the resize token button point.
What would be a use case for the "Is drawing" option on a character token editor?

**Comment by Blue64** [comment]
Resize Token without needing to place it on the Virtual Table Top, in order to do that function you'll need to have a maximum Size parameter for the image so you can adjust the Scale accordingly.

100×50 = 80×40 = 60×30 = 40×20 = 20×10

The difference between each size of image is the maximum number of Pixels available, so Roll20 for example uses 70×70 per 1×1 Grid, meaning that it would Resize to 70×35.

As far as why to mark it as a drawing? Ask Roll20, it's their function. They have it on the right click of the Tokens, alongside Flip Vertical & Flip Horizontal.

I also noticed that the Save to Default Token option strips the Current information on any Bar that is not linked to a stat, as well as resetting the orientation (which is why I noticed the orientation being lacking)

**Comment by SSStormy** [comment]
https://github.com/SSStormy/roll20-enhancement-suite/commit/93d7e3b3a8f0a67cf33f80d9faf6708be899df33 

The editor already exposes width/height edit fields.

**Comment by Blue64** [comment]
Yeah, but it doesn't expose the feature you added. The Width/Height fields were already exposed in the Resize Token Menu on Roll20, your Menu simply consolidated everything, but you didn't include the piece that you added to the Token Context Menu into the consolidation. It's not much work to do it, you simply Store the current status of the "move to top left" box, tell it that the status is set to off, then send it to the Resize scripts, then once the Resize is complete; you simply replace the "Move to Top Left" setting with the previously saved variable, then Apply the results to the correct Fields, and then update the fields. You already have everything already in place to do it, and I'm assuming you have it automatically check the Boolean Check Box for the Token getting moved as a subsection of the Resize Scripts instead of its own modular section. If they are a separate call, you wouldn't even need to store the Boolean flag.

**Comment by SSStormy** [comment]
I'm having a hard time understanding what exactly you are trying to say.

A manual width/height field is sufficient enough for the token editor as it has no concept of what a page is.

**Comment by Blue64** [comment]
... you know what? I'm going to get you a series of screenshots since Words are not working.

**Comment by Blue64** [comment]
Put this:
![screenshot_20181202-065438](https://user-images.githubusercontent.com/15118932/49339991-76005900-f5ff-11e8-87ab-9b357d9fa6f5.png)
In this:
![screenshot_20181202-065540](https://user-images.githubusercontent.com/15118932/49340006-94665480-f5ff-11e8-8340-c7224e9e755c.png)

**Comment by Blue64** [comment]
I want to clarify that I am not talking about the settings menu, but the functionality of the selected menus; by which I mean:

- Character Token Page
  - Token Resize Option

**Comment by Blue64** [comment]
Token Resize uses the Size of the current Virtual Table Top Page to figure out how big to make the Token.

If I have a 10×5 Image, and a 5×20 page, the Token Resize will see (10>5) & (5<20) so it shrinks the Image to 5×2.5 to fit within the 5×20

- Properties:
  - Image Size:
    - 10×5
  - Page Size:
    - 5×20
  - Token Resize Comparison:
    - Height: (10>5)
    - Width: (5<20)
  - Resize Token Results:
    - 5×2.5

My suggestion is to use the Default Token's Current Size Settings in place of the Page Size

**Comment by Blue64** [comment]
I'm going to be able to use my laptop for screenshots in a few hours, so don't worry if you are still confused, there is a LOT more specific visual explanation on the way, complete with color coded highlighting and numbers for reference.

**Comment by SSStormy** [comment]
Don't worry I get the idea now.
But to reiterate, I don't see the point of doing this. Token editor has no concept of what a page is and it already exposes width/height fields. This feels a bit too unnecessarily complex.

**Comment by Blue64** [comment]
If you get it, then you understand that it is extremely simple and entirely removes the need for a Page.

**Comment by Blue64** [comment]
If I knew how to do this myself, I could create the entire suggestion in under an hour, complete with the pull & merge request.

- I don't speak GitHub Code
- I don't speak JSON
- I haven't spoken JavaScript since I played RuneScape over a Decade ago

I would love to say it to you in a language you understand, but I don't know any language you use here, so I am going to say this in the simplest Code Based English I can conceive:

- Page.Max.Width = New.Token.Width
- Page.Max.Height = New.Token.Height
- Move.Token.TopLeft = 0
- GoTo, (Token.Resize)
- (Token.Resize) Executes, Returns
- New.Token.Width = Updated.Selected.Token.Width
- New.Token.Height = Updated.Selected.Token.Height

It is really that simple. Variable Height/Width listed in the Character Token Editor becomes the variables the pre-existing Token Resize command already uses. I have now explained that 6 times, 6 different ways. If you still don't get it, I will Photoshop the Token Resize button onto the Character Token Editor Page, right below the already existing Width & Height boxes, to literally show you what I mean.

**Comment by Blue64** [comment]
It doesn't require any Selected Token, it doesn't require a Page, it simply uses the already existing Data listed on the Character Token Editor to execute the Token Resize Scripts, and then updates the Fields with the results (7th time)
