### ISSUE TITLE
Transmogrifier Blank

### ISSUE THREAD

**Issue by jwperry** [SSStormy/roll20-enhancement-suite#143]
I noticed that the transmogrifier window is blank when I load a Roll20 game with VTT Enhancement Suite enabled. If I disable VTT Enhancement Suite and reload, the lists for both games I'm attempting to move objects between populate as normal.

This is on Google Chrome version 75.0.3770.100 (Official Build) (64-bit). VTT Enhancement Suite version 1.15.15.

Thanks for all of your hard work! VTT Enhancement Suite is amazing.

![Untitled](https://user-images.githubusercontent.com/13172425/60772059-bfd98200-a0ad-11e9-8d90-618a901d028d.png)

**Comment by Bathtor** [comment]
I've had this a few times as well, but reloading usually solved the issue.
I think the "disable VTT Enhancement Suite"-part is optional (at least for me).

**Comment by jwperry** [comment]
Interesting. I just tried it again while leaving VTT ES turned on the whole time, and found that reloading the page does not solve it for me, but closing the transmogrifier and reopening it does.

So...it seems like in actuality, the first time I open it after loading the page, it fails, but closing it and opening it again, it works.

I guess that probably still qualifies as a bug of some sort, but yeah, seems like that's a simple enough workaround for most people. As long as I don't have to flip the extension on/off, I'm not too worried about it. Thanks @Bathtor !

**Comment by Bathtor** [comment]
Ah, you are right, I actually remembered wrong. The same is true for me. 
It was opening and closing the transmogrifier, not reloading that worked in my case as well.
Cheers @jwperry :)

**Comment by SSStormy** [comment]
This is a wontfix known issue that only happens on Chrome. Sorry about that.

**Comment by kennethburgener** [comment]
Curious why this is a known issue that "won't be fixed"?

Could a note be at least added to the "Chrome" page, so other users know how to work around this issue?
