### ISSUE TITLE
Possible Unnecessary Import in src/utils/R20.ts

### ISSUE THREAD

**Issue by missionz3r0** [SSStormy/roll20-enhancement-suite#144]
May seem a bit minor, but I was going through the code trying to get a sense of it and noticed that in R20.ts a import from ava is done, creating cb.

However, I see no use of cb within the file.

Am I missing something or is this import unnecessary?

**Comment by SSStormy** [comment]
Yeah it seems to be unnecessary, it looks like something my IDE must have generated while trying to be "useful".

**Comment by missionz3r0** [comment]
Mind if I make a PR to remove it?

I'm using the utils of the enhancement suite in another project, and that import adds a lot of dependencies to that file.

**Comment by SSStormy** [comment]
Go ahead
