### ISSUE TITLE
Firefox Issue

### ISSUE THREAD

**Issue by Mad-Tinker** [SSStormy/roll20-enhancement-suite#149]
for some reason i keep getting Roll20es extension is required even though it is already installed, I have tried uninstalling and reinstalling it. I moved to Firefox because of chrome abandoning support for you.

![Screenshot (7)](https://user-images.githubusercontent.com/57013626/67592705-fb17c380-f725-11e9-9f1c-22eead0af128.png)

![Screenshot (8)](https://user-images.githubusercontent.com/57013626/67592916-86915480-f726-11e9-907d-e8ad897ff73f.png)

**Comment by SSStormy** [comment]
Not a VTTES issue but should be fixed.
