### ISSUE TITLE
Feature Request - Ability to update, rather than add duplicates, when importing

### ISSUE THREAD

**Issue by gludington** [SSStormy/roll20-enhancement-suite#159]
The Bulk Import/Export of Macros is extremely useful when creating a set of macros for importing from one game into another.  A feature to specify to overwrite existing macros rather than always add duplicates would be useful for cases when a library of macros is updated in one game and needs to be ported back into another game that had earlier versions of those same macros.

[This pull request](https://github.com/SSStormy/roll20-enhancement-suite/pull/158) has one possible implementation -- whereby a dropdown menu in the import screen allows to specify an "ImportStrategy" -- with the two options being ADD (the default, which performs the current behavior) or UPDATE_FIRST_MATCH, which will update the contents of the first macro in the current set with a matching name if found, and add if there is no match.

**Comment by SSStormy** [comment]
:+1: https://github.com/SSStormy/roll20-enhancement-suite/commit/d6beb8090a750784e21987e850275d074ccae7f5

**Comment by gludington** [comment]
Thank you, both for looking at it and the improvements to the PR you made.
