### ISSUE TITLE
Animated Background Scaling

### ISSUE THREAD

**Issue by BruceBeitman** [SSStormy/roll20-enhancement-suite#162]
Maybe I'm missing how to do this properly, but I believe with the change in roll20's zooming the map and token scaling is now not matching? Please see the attachments for examples, but if I understand what's happening, the animated background is not scaling but the tokens are? Any suggestions or fix is appreciated, thanks!

<img width="1006" alt="Animaged-Background-27" src="https://user-images.githubusercontent.com/12159090/73138793-c3762b80-4034-11ea-8c20-9f2eb7e7ca2d.png">
<img width="995" alt="Animated-Background-37" src="https://user-images.githubusercontent.com/12159090/73138794-c3762b80-4034-11ea-8b43-d90c89e54421.png">

**Comment by SSStormy** [comment]
Fixed as of 1.15.21
