### ISSUE TITLE
Music files don't import

### ISSUE THREAD

**Issue by hilstad** [SSStormy/roll20-enhancement-suite#164]
When I try to import a music track that I own into the Roll20 jukebox, I receive the error message 
Error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
I have tried both .mp3 and .flac files.

**Comment by SSStormy** [comment]
The playlist importer only imports what has been exported through the playlist exporter.

If you want to import your own audio files, use Roll20's My Audio or VTTES' LibreAudio (for which only raw media files will work like [this](https://upload.wikimedia.org/wikipedia/commons/f/f1/Algemene_sfeer_van_de_Kleine_Doelenzaal_bij_aanvang_concert_-_SoundCloud_-_Beeld_en_Geluid.ogg), meaning you'll have to find a place to host them)
