### ISSUE TITLE
Newly created module is not being loaded

### ISSUE THREAD

**Issue by OLStefan** [SSStormy/roll20-enhancement-suite#169]
I have created a new module on my fork of this repo.

I have created a new folder int he modules directory, and created a Cnfig.js and Module.ts in this folder. I created them using the other modules as template.

Then I added my config to the Config in the Configs.js in the source directory. This seems to be working correctly, as i now have a new entry in the settings menu.

My problem is that my module does not seem to be loaded, as it does not appear in the console when launching a Roll20 game, in contrast to the already existing modules.

Is there somewhere I have to add my new module to, like the root Configs.js for my new config, so that my new module is loaded?

**Comment by OLStefan** [comment]
I've been able to resolve my issue here. While some changes (like the new config) are loaded when I refresh the page, the new module is not. However, it was correctly loaded after restarting my browser.

**Comment by SSStormy** [comment]
I'd also like to point out that the webpack build system doesn't add new files into the build loop, meaning if you start the build loop and add a new files, you'll have to restart the build loop.
