### ISSUE TITLE
Compact Token Menu doesn't work on Chrome

### ISSUE THREAD

**Issue by sillvva** [SSStormy/roll20-enhancement-suite#85]
I saw that this was a feature, but I can't figure out how to configure it. Wasn't sure where else to ask this.

**Comment by SSStormy** [comment]
Are you using Chrome because it looks like that module is broken on Chrome.

**Comment by sillvva** [comment]
Yeah

**Comment by SSStormy** [comment]
Looks like some other modules aren't working properly on Chrome too. I'll look into it.

**Comment by SSStormy** [comment]
Okay, looks like 817d4239dcda8aa08b128d2e63f23f5a0f079991 fixes it on my end. Could you try running a bug85 branch build on your end for a sanity check?
[r20es_1.0.0.7-14-g817d423_chrome.zip](https://github.com/SSStormy/roll20-enhancement-suite/files/2350758/r20es_1.0.0.7-14-g817d423_chrome.zip)

**Comment by sillvva** [comment]
Works great. I also didn't realize that the individual checkbox options had
sub menus.
